// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.providerboilerplate;

import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.util.Optional;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("provider-boilerplate");
    public Optional<Boolean> itsasecret() {
        return Codegen.booleanProp("itsasecret").config(config).get();
    }
}
