// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.providerboilerplate;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProviderArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProviderArgs Empty = new ProviderArgs();

    @Import(name="itsasecret", json=true)
    private @Nullable Output<Boolean> itsasecret;

    public Optional<Output<Boolean>> itsasecret() {
        return Optional.ofNullable(this.itsasecret);
    }

    private ProviderArgs() {}

    private ProviderArgs(ProviderArgs $) {
        this.itsasecret = $.itsasecret;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProviderArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProviderArgs $;

        public Builder() {
            $ = new ProviderArgs();
        }

        public Builder(ProviderArgs defaults) {
            $ = new ProviderArgs(Objects.requireNonNull(defaults));
        }

        public Builder itsasecret(@Nullable Output<Boolean> itsasecret) {
            $.itsasecret = itsasecret;
            return this;
        }

        public Builder itsasecret(Boolean itsasecret) {
            return itsasecret(Output.of(itsasecret));
        }

        public ProviderArgs build() {
            return $;
        }
    }

}
