// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.providerboilerplate;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.util.Objects;


public final class RandomComponentArgs extends com.pulumi.resources.ResourceArgs {

    public static final RandomComponentArgs Empty = new RandomComponentArgs();

    @Import(name="length", required=true)
    private Output<Integer> length;

    public Output<Integer> length() {
        return this.length;
    }

    private RandomComponentArgs() {}

    private RandomComponentArgs(RandomComponentArgs $) {
        this.length = $.length;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RandomComponentArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RandomComponentArgs $;

        public Builder() {
            $ = new RandomComponentArgs();
        }

        public Builder(RandomComponentArgs defaults) {
            $ = new RandomComponentArgs(Objects.requireNonNull(defaults));
        }

        public Builder length(Output<Integer> length) {
            $.length = length;
            return this;
        }

        public Builder length(Integer length) {
            return length(Output.of(length));
        }

        public RandomComponentArgs build() {
            if ($.length == null) {
                throw new MissingRequiredPropertyException("RandomComponentArgs", "length");
            }
            return $;
        }
    }

}
