// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.providerboilerplate;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.providerboilerplate.RandomComponentArgs;
import com.pulumi.providerboilerplate.Utilities;
import java.lang.Integer;
import java.lang.String;
import javax.annotation.Nullable;

@ResourceType(type="provider-boilerplate:index:RandomComponent")
public class RandomComponent extends com.pulumi.resources.ComponentResource {
    @Export(name="length", refs={Integer.class}, tree="[0]")
    private Output<Integer> length;

    public Output<Integer> length() {
        return this.length;
    }
    @Export(name="password", refs={String.class}, tree="[0]")
    private Output<String> password;

    public Output<String> password() {
        return this.password;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public RandomComponent(java.lang.String name) {
        this(name, RandomComponentArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public RandomComponent(java.lang.String name, RandomComponentArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public RandomComponent(java.lang.String name, RandomComponentArgs args, @Nullable com.pulumi.resources.ComponentResourceOptions options) {
        super("provider-boilerplate:index:RandomComponent", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), true);
    }

    private static RandomComponentArgs makeArgs(RandomComponentArgs args, @Nullable com.pulumi.resources.ComponentResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? RandomComponentArgs.Empty : args;
    }

    private static com.pulumi.resources.ComponentResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.ComponentResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.ComponentResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.ComponentResourceOptions.merge(defaultOptions, options, id);
    }

}
