// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.providerboilerplate;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.providerboilerplate.RandomArgs;
import com.pulumi.providerboilerplate.Utilities;
import java.lang.Integer;
import java.lang.String;
import javax.annotation.Nullable;

@ResourceType(type="provider-boilerplate:index:Random")
public class Random extends com.pulumi.resources.CustomResource {
    @Export(name="length", refs={Integer.class}, tree="[0]")
    private Output<Integer> length;

    public Output<Integer> length() {
        return this.length;
    }
    @Export(name="result", refs={String.class}, tree="[0]")
    private Output<String> result;

    public Output<String> result() {
        return this.result;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Random(java.lang.String name) {
        this(name, RandomArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Random(java.lang.String name, RandomArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Random(java.lang.String name, RandomArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("provider-boilerplate:index:Random", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Random(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("provider-boilerplate:index:Random", name, null, makeResourceOptions(options, id), false);
    }

    private static RandomArgs makeArgs(RandomArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? RandomArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Random get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Random(name, id, options);
    }
}
