template: native
provider: provider-boilerplate
major-version: 0
providerDefaultBranch: main
publishRegistry: false
providerVersion: github.com/pulumi/pulumi-provider-boilerplate/provider.Version
parallel: 3
sdkModuleDir: sdk/go/pulumi-provider-boilerplate
esc:
    enabled: true
    environment: imports/github-secrets
# For some reason this is required. If it's omitted all of the env keys get duplicated.
envOverride:
    FOO: BAR
